#!/bin/sh

# We do something a bit special here. Since this suite contains intentional
# errors, we don't want it to be run when we run a recursive suite by default.

DIRS=". dir.one two nocover assertiondemo"

for i in $DIRS; do
    cp $i/.pry.inactive $i/.pry
done

../../pry $*

for i in $DIRS; do
    rm $i/.pry
done
