#!/bin/sh

# We do something a bit special here. Since this suite contains intentional
# errors, we don't want it to be run when we run a recursive suite by default.

cp .pry.inactive .pry
cp dir.one/.pry.inactive dir.one/.pry
../../pry $*
rm dir.one/.pry
rm .pry
